[package]
name = "aoahid"
version = "4.2.0"
edition = "2021"
description = "Typed ownership and node-reference wrappers for libaoahid"
license = "MIT"
homepage = "https://github.com/nemarpuc/libaoahid"
repository = "https://github.com/nemarpuc/libaoahid"

[dependencies]
aoahid-sys = { path = "../aoahid-sys", version = "4.2.0" }
